class ZCX_BACKGROUND_JOB definition
  public
  inheriting from /IWBEP/CX_MGW_BASE_EXCEPTION
  final
  create public .

public section.

  interfaces IF_T100_DYN_MSG .

  methods CONSTRUCTOR
    importing
      !TEXTID like IF_T100_MESSAGE=>T100KEY optional
      !PREVIOUS like PREVIOUS optional
      !MESSAGE_CONTAINER type ref to /IWBEP/IF_MESSAGE_CONTAINER optional
      !HTTP_STATUS_CODE type /IWBEP/MGW_HTTP_STATUS_CODE optional
      !HTTP_HEADER_PARAMETERS type /IWBEP/T_MGW_NAME_VALUE_PAIR optional
      !SAP_NOTE_ID type /IWBEP/MGW_SAP_NOTE_ID optional
      !MSG_CODE type STRING optional
      !EXCEPTION_CATEGORY type TY_EXCEPTION_CATEGORY optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_BACKGROUND_JOB IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
PREVIOUS = PREVIOUS
MESSAGE_CONTAINER = MESSAGE_CONTAINER
HTTP_STATUS_CODE = HTTP_STATUS_CODE
HTTP_HEADER_PARAMETERS = HTTP_HEADER_PARAMETERS
SAP_NOTE_ID = SAP_NOTE_ID
MSG_CODE = MSG_CODE
EXCEPTION_CATEGORY = EXCEPTION_CATEGORY
.
clear me->textid.
if textid is initial.
  IF_T100_MESSAGE~T100KEY = IF_T100_MESSAGE=>DEFAULT_TEXTID.
else.
  IF_T100_MESSAGE~T100KEY = TEXTID.
endif.
  endmethod.
ENDCLASS.
